version: "3.2"
services:
  host:
    user: ${USER}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=${USER}
        - IMAGE=${IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}-host
    environment:
      - SHELL=${SHELL}
      - TZ=${TZ}
      - LANG=${LANG}
      - HOST=${HOST}
    ports:
      - 9090:9090
      - 9292:9292
    volumes:
      - ..:/home/${USER}/workspace:cached
      - ${HOME}/.ssh:/home/${USER}/.ssh
      - ${HOME}/.gitconfig:/home/${USER}/.gitconfig
      - ${HOME}/.gnupg:/home/${USER}/.gnupg
    links:
      - redis-db
      - mongo-db
      - postgres-db
    working_dir: /home/${USER}/workspace/projects
    command: sleep infinity

  redis-db:
    image: redis
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    volumes:
      - ../db-data/redis:/data:delegated
    ports:
      - 6379:6379

  mongo-db:
    image: mongo
    container_name: ${COMPOSE_PROJECT_NAME}-mongo
    volumes:
      - ../db-data/mongo:/data/db:delegated
    ports:
      - 27017:27017

  postgres-db:
    image: postgres
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    volumes:
      - ../db-data/postgres:/var/lib/postgresql/data:delegated
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres_passwd
