version: "3.2"
services:
  host:
    user: ${USER}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=${USER}
        - PASSWD=${PASSWD}
    container_name: codepraise-host
    ports:
      - 9090:9090
      - 9292:9292
    volumes:
      - ..:/home/${USER}/workspace:cached
      - ${HOME}${USERPROFILE}/.ssh:/home/${USER}/.ssh
      - ${HOME}${USERPROFILE}/.gitconfig:/home/${USER}/.gitconfig
      - ${HOME}${USERPROFILE}/.gnupg:/home/${USER}/.gnupg
    links:
      - redis-db
      - mongo-db
      - postgres-db
    working_dir: /home/${USER}/workspace/projects
    command: sleep infinity

  redis-db:
    image: redis
    container_name: codepraise-redis
    volumes:
      - ../db-data/redis:/data:delegated
    ports:
      - 6379:6379

  mongo-db:
    image: mongo
    container_name: codepraise-mongo
    volumes:
      - ../db-data/mongo:/data/db:delegated
    ports:
      - 27017:27017

  postgres-db:
    image: postgres
    container_name: codepraise-postgres
    volumes:
      - ../db-data/postgres:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres_passwd
